functional:
  - Пользователь должен иметь возможность обратиться в службу поддержки и получить помощь в решении проблем.
  - Пользователь должен иметь возможность отслеживать статус доставки своего заказа и получать уведомления об изменениях статуса.
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Пользователь должен иметь возможность оформить заказ и выбрать способ доставки и оплаты.
  - Пользователь должен получать уведомления о статусе своего заказа.
  - Пользователь должен иметь возможность создавать свой список желаний и сохранять в нем понравившиеся товары.
  - Администратор сайта должен иметь возможность добавлять, редактировать и удалять товары.
  - Администратор сайта должен иметь возможность просматривать и управлять заказами.
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть доступен на различных устройствах.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть доступен на различных устройствах.
  - Сайт должен быть быстрым и иметь высокую производительность.
  - Сайт должен соответствовать стандартам веб-разработки и быть легко поддерживаемым.
  - Сайт должен иметь удобную навигацию и структуру для удобства пользователей.
  - Сайт должен быть легко масштабируемым для возможности добавления новых функций и развития бизнеса.
  - Сайт должен соответствовать законодательству и правилам торговли в интернете.
  - Сайт должен быть оптимизирован для поисковых систем и иметь хороший SEO-рейтинг.
  - Сайт должен быть поддерживаемым и обновляемым для обеспечения безопасности и стабильной работы.
  - Сайт должен иметь систему резервного копирования данных для предотвращения потери информации.
implicit:
  - Интернет-магазин должен иметь удобный интерфейс
  - На сайте должна быть Политика конфиденциальности и файлов cookie
  - Макет магазина должен быть адаптирован к мобильным устройствам.
  - Магазин должен быть одностраничным приложением (SPA) и не перезагружать страницу во время использования.
  - Каталог товаров должен быть удобным для поиска и фильтрации.
  - Каталог товаров должен отображать название, рейтинг, цену и скидку каждого товара.
  - Пользователь должен иметь возможность добавлять несколько товаров в корзину.
  - Пользователь должен иметь возможность удалять товары из корзины.
  - Магазин должен иметь страницу оплаты.
  - Корзина должна храниться в сессии браузера для легкого доступа и сохранения.
